### ISSUE TITLE
Error running SAE in evaluation notebook

### ISSUE THREAD

**Issue by mnida** [jbloomAus/mats_sae_training#4]
Problem: When running the evaluating_your_sae.ipynb I get an error when trying to do the L0 test in the 3rd code block.

More specifically, when running the sparse_autoencoder(cache[sparse_autoencoder.cfg.hook_point])

Since I didn't have a chance to train the model myself and am using the 
_"sparse_autoencoder_gpt2-small_blocks.10.hook_resid_pre_6144:v2/1200001024_sparse_autoencoder_gpt2-small_blocks.10.hook_resid_pre_6144.pt"_ 
checkpoint, I wanted to flag this in case someone else ran into this issue.

If I missed something obvious, I apologize! Thank you for open-sourcing this research :)

The last line in the screenshot says 'NoneType' object has no attribute 'sum'.
<img width="882" alt="Screen Shot 2024-02-06 at 5 18 54 PM" src="https://github.com/jbloomAus/mats_sae_training/assets/33556500/e8d3a496-dee8-4e7a-8278-a70d2f05d6e2">

**Comment by jbloomAus** [comment]
Apologies, you should set `sparse_autoemcoder.cfg.use_ghost_grads = False`.

I'll sort this out by default shortly. It's a train vs run time difference
I need to handle.

**Comment by mnida** [comment]
Gotcha. Thanks for the quick response! I am getting another error now:
 but I will

**Comment by jbloomAus** [comment]
Hey, so the thing with ghost grads is they are tied to the sparse_autoencoder being in train vs eval mode. I should have added some kinda helpful error / warning here about this. If you do `sparse_autoencoder.eval()` instead of turning ghost grads off in the config, this would be better in the future. 

With the image above, I'm a little confused since I think the line you highlighted is the line running the error. It's probably the output of the SAE is now a tuple of length 5 not 4 (since it contains the ghost grad loss) so you should find where that's happening. 

Happy to help if you can show me more of the code (especially if it's in the tutorial which I want to overhaul).

**Comment by jbloomAus** [comment]
This should be fixed. I'm going to close but feel free to re-open if this is still an issue.

**Comment by mnida** [comment]
Great @jbloomAus ! Fixed for me. Appreciate it and awesome work
